"""init jobs/pages/images/events

Revision ID: a73cb35dc5f1
Revises: 
Create Date: 2026-09-06 01:39:39.330853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a73cb35dc5f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PREFLIGHT', 'RENDERING', 'OCR', 'TRANSCRIBING', 'ASSEMBLING', 'QA', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', name='jobstatus'), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('output_dir', sa.String(length=1024), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_job_id'), 'events', ['job_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('asset_path', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.Enum('NATIVE', 'CROP', name='imagesource'), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alt_text', sa.String(length=512), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('referenced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_job_id'), 'images', ['job_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OCR', 'TRANSCRIBED', 'VERIFIED', 'NEEDS_REVIEW', 'FAILED', name='pagestatus'), nullable=False),
    sa.Column('render_dpi', sa.Integer(), nullable=True),
    sa.Column('ocr_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('coverage_score', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('omissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_page_hash', sa.String(length=64), nullable=True),
    sa.Column('render_hash', sa.String(length=64), nullable=True),
    sa.Column('ocr_hash', sa.String(length=64), nullable=True),
    sa.Column('markdown_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'page_number')
    )
    op.create_index(op.f('ix_pages_job_id'), 'pages', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_job_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_images_job_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_events_job_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('jobs')
    # ### end Alembic commands ###
    # Native PG enums are NOT dropped with their tables: drop explicitly or
    # any later re-upgrade fails with 'type "jobstatus" already exists'.
    for _name, _labels in (
        ("jobstatus", ('QUEUED', 'PREFLIGHT', 'RENDERING', 'OCR', 'TRANSCRIBING',
                       'ASSEMBLING', 'QA', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED')),
        ("pagestatus", ('PENDING', 'OCR', 'TRANSCRIBED', 'VERIFIED', 'NEEDS_REVIEW', 'FAILED')),
        ("imagesource", ('NATIVE', 'CROP')),
    ):
        sa.Enum(*_labels, name=_name).drop(op.get_bind(), checkfirst=True)
